services:
  order:
    container_name: order
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://events-db:5432/events?currentSchema=orders_space
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - order-pg-volume:/var/lib/postgresql
    extends:
      file: ../compose-config.yml
      service: microservice-base
volumes:
  order-pg-volume:

networks:
  events:
    driver: bridge