services:
  payment:
    container_name: payment
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DD_SERVICE=payment-service
      - DD_VERSION=1.0.0
    extends:
      file: ../compose-config.yml
      service: microservice-base

networks:
  events:
    driver: bridge