services:
  shared-network:
    networks:
      - events
  microservice-base:
    extends:
      service: shared-network
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      - KAFKA_BROKER=kafka:19092
    depends_on:
      kafka:
        condition: service_healthy