include:
  - ./compose.kafka.yml
  - ./compose.db.yml
  - ./order/compose.yml
  - ./payment/compose.yml
  - ./notification/compose.yml

networks:
  events:
    driver: bridge

volumes:
  events-pg-volume: