spring:
  application:
    name: order

  cloud:
    function:
      definition: updateOrder # name of the function defined in the code
    stream:
      bindings:
        updateOrder-in-0:
          destination: payment-processed
          group: ${spring.application.name}
        createOrder-out-0:
          destination: order-created # destination name in the message broker
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:localhost:9092}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1234/vendra?currentSchema=orders_space
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    default-schema: orders_space
    schemas: orders_space
    create-schemas: true
  jpa:
    properties:
      hibernate:
        default_schema: orders_space

logging:
  level:
    org:
      apache:
        kafka: WARN
