spring:
  application:
    name: order

  cloud:
    function:
      definition: updateOrder # name of the function defined in the code
    stream:
      bindings:
        updateOrder-in-0:
          destination: payment-processed
          group: ${spring.application.name}
          consumer:
            concurrency: 1 # Default: 1 Kafka consumer thread (increase to consume partitions in parallel)
        createOrder-out-0:
          destination: order-created # destination name in the message broker
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:localhost:9092}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5423/events?currentSchema=orders_space
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    default-schema: orders_space
    schemas: orders_space
    create-schemas: true
  jpa:
    properties:
      hibernate:
        default_schema: orders_space

  # Enable Virtual Threads (Project Loom, Java 21+)
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      apache:
        kafka:
          clients:
            consumer:
              internals: ERROR
